- menu_name: "Links"

- name: "Contact"
  url: "/contact/"
  title: "Contact"

- name: "RSS"
  url: "/feed.xml"
  title: "Subscribe to RSS"

- name: "sitemap.xml"
  url: "/sitemap.xml"
  title: "Sitemap"
